version: "3"
services:
  frontend:
    image: frontend
    restart: always
    container_name: frontend
    build: app/frontend
    init: true
    env_file:
      - ./.env
    ports:
      - 80:3000
    volumes:
      - front:/home/src
      - /home/src/node_modules

  backend:
    image: backend
    restart: always
    container_name: backend
    build: app/backend
    init: true
    env_file:
      - ./.env
    ports:
      - 81:80
    volumes:
      - back:/home/src
      - /home/src/node_modules


  postgresql:
    image: postgres
    restart: always
    user: postgres
    env_file:
      - ./.env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  front:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/app/frontend/src
  back:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/app/backend/src